### ISSUE TITLE
Stream not loading

### ISSUE THREAD

**Issue by Davincible** [bootsie123/F1-Web-Viewer#11]
![image](https://user-images.githubusercontent.com/25869544/120799755-6f8c2880-c53f-11eb-9499-96f5f50768a1.png)

Netlify version not working for me

**Comment by bootsie123** [comment]
This is due to a recent update to the F1TV API that adds CORS to live events. For right now, I created a fix that uses a free CORS proxy for live events. This will cause everything to run a little bit slower.

The patch is being deployed under v1.7.2

**Comment by bootsie123** [comment]
Looks like the fix works. Just make sure to re-add any videos you have in your layout

**Comment by giantorth** [comment]
I am getting this same message with chrome on mac and windows, tested both on your hosted version and a docker image on my server.  My docker is running 1.7.4.

**Comment by bootsie123** [comment]
Hm. What operating system and browser version are you using?

**Comment by giantorth** [comment]
The docker container is running on a Debian 10 host.  I've tried the latest chrome and safari on OSX Big Sur, chrome and edge on a windows 10 machine.
Even trying various races and feeds seems to make no difference.  I'm able to use race control with the same account on my windows computer.

**Comment by bootsie123** [comment]
Found the issue... Unfortunately, it looks like they just recently enabled CORS for all videos. Not just the live races. It should be going through a local CORS proxy when self hosting it so I'll look into that

**Comment by giantorth** [comment]
![image](https://user-images.githubusercontent.com/56210456/121690542-d39c7880-ca7a-11eb-95c0-2794e5b47b3a.png)
Looking at my browser console yes there is in fact a CORS error.

**Comment by giantorth** [comment]
It seems the first request hits the internal proxy but then the browser client tries pulling the m3u file directly without using the proxy.

**Comment by 2fst4u** [comment]
Before I open a new issue for this, would this issue also cause nothing to play at all? I don't get any errors but every player window that I add just does nothing when I click the play icon. It just stays black.

**Comment by bootsie123** [comment]
Hm. That's odd. Do you get an errors in your browser's console log?

**Comment by 2fst4u** [comment]
A couple. I'll open a new issue.
