### ISSUE TITLE
Background White in Full Screen Mode

### ISSUE THREAD

**Issue by pvanb** [bootsie123/F1-Web-Viewer#12]
**Describe the bug**
When in full screen mode the background is white, creating distracting white spaces on the screen

**To Reproduce**
1. Create a layout that doesn't fill 100% of the browser
2. Make the browser full screen
3. See the background is white

**Expected behavior**
The description [on Reddit](https://www.reddit.com/r/F1TV/comments/npgd82/new_f1_web_viewer_a_new_way_to_watch_f1/) suggests full screen mode should make the background dark, so that's what I was expecting.

**Screenshots**
Actual: ![Screen Shot 2021-06-04 at 1 33 02 PM](https://user-images.githubusercontent.com/823278/120842162-5af96180-c53a-11eb-945e-ee1dba916564.png)
Expected: ![Screen Shot 2021-06-04 at 1 33 22 PM](https://user-images.githubusercontent.com/823278/120842221-6cdb0480-c53a-11eb-8836-1257a43c90f5.png)

**Desktop (please complete the following information):**
 - OS: macOS 10.15.7
 - Browser Safari 14.1.1

**F1TV Account (please complete the following information):**
 - Subscription Type: Pro
 - Country: Canada

**Comment by bootsie123** [comment]
Hi! Thanks for the bug report! I'll try to get a fix for this done before practice 3 tomorrow. It looks like the way I am detecting fullscreen mode isn't entirely cross-compatible on MacOS. I'll let you know when the fix is up!

**Comment by bootsie123** [comment]
Alright so after looking into the issue more it looks like it has to do with how browsers deal with putting themselves into fullscreen mode. Chrome seems to handle it like a regular fullscreen event while Safari seems to completely ignore it.

In terms of a solution, I think I'll probably add a combination of detecting the keyboard shortcuts for fullscreen and a fullscreen button in the pullout menu.

If anyone has any other possible solutions I'd be glad to hear them!

**Comment by pvanb** [comment]
I don't have a suggestion to auto-detect, especially if Safari is ignoring events.

However before I noticed that fullscreen mode was supposed to automatically make the background dark this was going to be a feature request to have a "dark mode" or just have the background of the video area dark/black to begin with.

**Comment by bootsie123** [comment]
I was thinking of something like that. That might end up just being easier, although the arrow for the sliding panel would still show instead of being hidden. I'll see what I can do

**Comment by bootsie123** [comment]
Ended up going creating a background toggle which will eventually evolve into a "dark mode" toggle
