### ISSUE TITLE
Hi, can you register this application for cors.bridged.cc usage?

### ISSUE THREAD

**Issue by softmarshmallow** [bootsie123/F1-Web-Viewer#30]
I found that https://f1webviewer.netlify.app feed.vue is using cors.bridged.cc.
From July 2021, application using cors proxy must register their application. 
https://github.com/bridgedxyz/base/issues/23

**Comment by bootsie123** [comment]
Hi! I didn't see this, thanks for the heads up! I'll try to get that done right away. 

Also, I noticed you're from Bridged. Due to the nature of my site it's highly possible that it's causing a fair bit of usage. Let me know if this ever becomes of a problem! I'd be more than willing to try to work something out with you guys

**Comment by softmarshmallow** [comment]
Sure no problem. we love opensource, we'll try our best to keep this project able to use any bridged service free forever!
(And contact if the usage exceeds our limitation)

Have a great day :)

**Comment by bootsie123** [comment]
You too! ...and submitted the form! Feel free to reach out of you have any questions or need anything else from me

**Comment by softmarshmallow** [comment]
Sure. And may I ask if it would be ok to refer to this repo on "Who is using BASE @ README" [here](https://github.com/bridgedxyz/base#who-is-using-base) ?

Plus, would be lovely having a small acknowledgement on your README too (about [base](https://github.com/bridgedxyz/base))!

**Comment by bootsie123** [comment]
> And may I ask if it would be ok to refer to this repo on "Who is using BASE @ README"

Sure!

> Plus, would be lovely having a small acknowledgement on your README too

Yes definitely! Your service literally saved by me on launch week for this project when F1TV decided to implement CORS. For that, many thanks!

> got your form. will get back to you personally with api key

Awesome! Thanks so much!
