### ISSUE TITLE
Feature request: Arm support for docker

### ISSUE THREAD

**Issue by 2fst4u** [bootsie123/F1-Web-Viewer#32]
Any possibility of Arm support for the docker image? Preferably in multi-arch tags for ease of use.

Thanks

**Comment by bootsie123** [comment]
Sure! I can look into this!

**Comment by bootsie123** [comment]
Added in v1.7.7

**Comment by bootsie123** [comment]
@2fst4u Sorry for the wait! The multi-arch docker image should be available now

**Comment by 2fst4u** [comment]
Brilliant it works perfectly!

Note this also fixes the issue in #33, the video plays straight away, no issues with black boxes.

Thanks!

**Comment by bootsie123** [comment]
Glad to hear it works now! I guess the issue had to due with the CORS proxy
