### ISSUE TITLE
F1-Web-Viewer username and password incorrect

### ISSUE THREAD

**Issue by Placemaster** [bootsie123/F1-Web-Viewer#36]
While logging in on Firefox, safari or chrome I do get the message that the username and password are incorrect.
Just open the website and try to log-in

MacBook Air 2021
Firefox, safari or chrome

**F1TV Account (please complete the following information):**
 - Subscription Type: Pro Annual
 - Country: the Netherlands

The username and password are accepted on the original website of the F1.

**Comment by bootsie123** [comment]
Hi! Thanks for the bug report. Everything seems to be working on my end. Could you verify that the username and password you're using is correct? Not sure if you have the password autosaved or not.

A few more questions. Do you use a VPN at all while watching F1? Also, if you wouldn't mind, could you post any error messages that appear in the console log of your web browser? Thanks!

**Comment by Placemaster** [comment]
Hi,

Yesterday the qualification and now the race it is working again.
So I don’t know why it was not working.
I am sure that the username and password were correct.

As soon I do experience the same I will come back to you.

Best Regards,
Erwin Bouwman

**Comment by bootsie123** [comment]
Gotcha. Glad it's working again. Definitely feel free to open this issue if it happens again. I know there were a few API changes recently, but those got reverted and I didn't think that included changes to initial authentication
