### ISSUE TITLE
Email validation routine doesn't allow domains with more than one tld

### ISSUE THREAD

**Issue by Bagpuss** [bootsie123/F1-Web-Viewer#4]
The isValidEmail() function is very simplistic and doesn't account for addresses with more than one top level domain, e.g. co.uk. This means that it is not possible for such users to log in at all at the moment.

Is it even worth validating the address at all? It only gets sent through to F1TV anyway :)

**Comment by bootsie123** [comment]
Now that’s a small oversight on my part. I’ll definitely have a fix before the end of the day for that. Thanks for the report!
