### ISSUE TITLE
404 error

### ISSUE THREAD

**Issue by NotTheRealTWCH** [bootsie123/F1-Web-Viewer#62]
**Describe the bug**
When accessing the locally hosted website via the URL "http://localhost:3000", I get a 404 error and the HTML page displays the text, "Cannot GET /". There's a content security policy that blocks the favicon from loading, but I'm not sure if that affects the overall loading of the HTML page.

**Screenshots**
![image](https://user-images.githubusercontent.com/7797656/159150096-f0a82bd5-642b-4931-a9fb-5bf70471225c.png)
![image](https://user-images.githubusercontent.com/7797656/159150146-794ceb97-0c32-4acb-9a5f-8ea77f7cd0f3.png)

**Desktop (please complete the following information):**
 - OS: Microsoft Windows 11 Pro (10.0.22000 Build 22000)
 - Browser: Firefox (98.0.1)

**Comment by bootsie123** [comment]
Hi! Thanks for posting this issue! I'm not sure if you mentioned this yet, but did you run `npm run build`?

**Comment by NotTheRealTWCH** [comment]
> 

Yeah I have. I don't think you can run the server without building it, am I correct?

**Comment by NotTheRealTWCH** [comment]
I've tried to go through the process again so you can see what's happening. There are some errors/warnings for deprecated dependencies I believe. @bootsie123 
![image](https://user-images.githubusercontent.com/7797656/159391244-dc4b1250-54f9-468c-be63-003000a08b99.png)
![image](https://user-images.githubusercontent.com/7797656/159391306-b1f37cf7-b1fb-48fc-8bca-c06bc41b2bb3.png)
![image](https://user-images.githubusercontent.com/7797656/159391384-21a06b50-150c-44a7-8331-ea66072507fd.png)

**Comment by bootsie123** [comment]
Ah. It seems that it fails while building the site which then causes none of the expected files to be created. Thus the 404 error.

I think you're probably right with it most likely being a combination of depreciated packages along with you using a different node and npm version.

Looking further, it seems to be an issue with webpack and node 17 according to [this issue](https://github.com/webpack/webpack/issues/14532). Could you try running `export NODE_OPTIONS=--openssl-legacy-provider` and then building the project again?

**Comment by NotTheRealTWCH** [comment]
> 

That worked. I'm on npm version 8.5.2 and node 17.7.2 by the way.

**Comment by bootsie123** [comment]
Awesome, glad that worked for you! This reminds me, I should probably update my node version to the LTS version. I think I'm using 12 or 14 right now
