### ISSUE TITLE
[Request] Single Channel Selection without Drag and Drop

### ISSUE THREAD

**Issue by anthonylavado** [bootsie123/F1-Web-Viewer#66]
**Describe the bug**
It's a bit more of a platform limitation. If viewing the website on a console (Xbox One X with Chromium Edge), the browser does not support drag and drop events, even with a mouse connected. As a result, it's not possible to start playback.

**Expected behavior/Feature Request**
If no streams are currently selected in the layout, a compromise would be to automatically add the first stream that is clicked on, without having to drag and drop it into the grid. If desired, this could be kept as an option like "Console" behind the Stream Type selector.

**Desktop (please complete the following information):**
 - OS: Xbox One X on March 9 2022 update (10.0.22000.3832)
 - Browser: Edge (Xbox)
 - Version: 97.0.1072.91

**F1TV Account (please complete the following information):**
 - Subscription Type: Pro
 - Country: Canada

**Comment by iebb** [comment]
I have made a working example of adding a fullscreen button, which clears the layout and add the corresponding stream occupying the full grid in beta branch of my fork.

https://github.com/iebb/F1-Web-Viewer/tree/beta

![image](https://user-images.githubusercontent.com/2127498/162628278-defdd027-a3f8-4f6b-be98-4a7bf8d84056.png)
